language: cpp

cache:
  apt: true
  directories:
    - $VCPKG_HOME

env:
  global:
    - VCPKG_HOME="$HOME/vcpkg"

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc-8 CXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
            - xvfb
      before_script:
        - travis_wait ./scripts/install-deps.sh
        - export DISPLAY=:99
        - sh -e /etc/init.d/xvfb start
      script:
        - travis_wait ./scripts/build.sh

    - os: osx
      osx_image: xcode11.4
      before_script:
        - travis_wait ./scripts/install-deps.sh
      script:
        - travis_wait ./scripts/build.sh

    - os: windows
      before_script:
        - travis_wait ./scripts/install-deps.bat
      script:
        - travis_wait ./scripts/build.bat
