language: c++

cache:
  directories:
    - $HOME/vcpkg

os:
  - linux
  - osx
dist: bionic
osx_image: xcode11.3
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
      - libglu1-mesa-dev

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_script:
  - source scripts/install-deps.sh

script:
  - mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE="$VCPKG_CMAKE_TOOLCHAIN" ..
  - travis_wait cmake --build .
  - ctest
