language: cpp

cache:
  apt: true
  directories:
    - $VCPKG_HOME
    - $SRC_DIR

env:
  global:
    - VCPKG_HOME="$HOME/vcpkg"
    - SRC_DIR="$HOME/src"

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc-8 CXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            # GLFW3 dependencies on linux
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
            # Offscreen rendering support in GLFW
            - libosmesa-dev
      services:
        - xvfb
      install:
        - travis_wait ./scripts/install-deps.sh
      before_script:
        - travis_wait ./scripts/build.sh
      script:
        - ./scripts/test.sh

    - os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          casks:
            - xquartz
      install:
        - travis_wait ./scripts/install-deps.sh
      before_script:
        - travis_wait ./scripts/build.sh
      script:
        # Use the bundled osmesa library in xquartz
        - sudo ln -s /usr/X11/lib/libOSMesa.8.dylib /usr/lib/libOSMesa.8.dylib
        - ./scripts/test.sh

    - os: windows
      install:
        - ./scripts/install-mesa.bat
        - travis_wait ./scripts/install-deps.bat
      before_script:
        - travis_wait ./scripts/build.bat
      script:
        - ./scripts/test.bat
