language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
      env:
        - CMAKE_CONFIGURATION=Release
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
      env:
        - CMAKE_CONFIGURATION=Debug
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - ./scripts/install-deps.sh

before_script:
  - mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/libexec/scripts/buildsystems/vcpkg.cmake ..

script:
  - travis_wait cmake --build build/
  - ctest
