language: cpp

cache:
  apt: true
  directories:
    - $VCPKG_HOME
    - $SRC_DIR

env:
  global:
    - VCPKG_HOME="$HOME/vcpkg"
    - SRC_DIR="$HOME/src"

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc-8 CXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglapi-mesa
            - libosmesa-dev
      install:
        - travis_wait ./scripts/install-deps.sh
      before_script:
        - travis_wait ./scripts/build.sh
      script:
        - ./scripts/test.sh

    - os: osx
      osx_image: xcode11.4
      addons:
        homebrew:
          packages:
            - meson
            - ninja
      install:
        - pip3 install mako
        - travis_wait ./scripts/install-mesa.sh
        - travis_wait ./scripts/install-deps.sh
      before_script:
        - travis_wait ./scripts/build.sh
      script:
        - ./scripts/test.sh

    - os: windows
      install:
        - ./scripts/install-mesa.bat
        - travis_wait ./scripts/install-deps.bat
      before_script:
        - travis_wait ./scripts/build.bat
      script:
        - ./scripts/test.bat
