language: c++

cache:
  apt: true
  directories:
    - $VCPKG_HOME

env:
  - VCPKG_HOME="$HOME/vcpkg"

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc-8
        - CXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - libxinerama-dev
            - libxcursor-dev
            - xorg-dev
            - libglu1-mesa-dev
    - os: osx
      osx_image: xcode11.4

before_script:
  - ./scripts/install-deps.sh

script:
  - mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE="$VCPKG_HOME/scripts/buildsystems/vcpkg.cmake" ..
  - travis_wait cmake --build .
  - ctest
