language: c++

matrix:
  include:
    - os: linux
      compiler: gcc
      env: CMAKE_CONFIGURATION=Release

    - os: linux
      compiler: gcc
      env: CMAKE_CONFIGURATION=Debug

before_install:
  - ./scripts/install-deps.sh

before_script:
  - mkdir build && cd build && cmake ..

script:
  - travis_wait cmake --build build/
  - ctest
