language: c++

cache:
  apt: true
  directories:
    - $VCPKG_HOME

env:
  - VCPKG_HOME="$HOME/vcpkg"

os:
  - linux
  - osx
dist: bionic
osx_image: xcode11.4
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - libxinerama-dev
      - libxcursor-dev
      - xorg-dev
      - libglu1-mesa-dev

matrix:
  exclude:
    - os: linux
      compiler: clang
    - os: osx
      compiler: gcc

before_script:
  - ./scripts/install-deps.sh

script:
  - mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE="$VCPKG_HOME/scripts/buildsystems/vcpkg.cmake" ..
  - travis_wait cmake --build .
  - ctest
