version: 2.1

commands:
  build:
    steps:
      - checkout
      - run:
          name: "CMake: Configure"
          command: "mkdir build/ && cd build/ && cmake -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake .."
      - run:
          name: "CMake: Build"
          command: "cmake --build .."
  test:
    steps:
      - run:
          name: "CMake: Test"
          command: "ctest"

executors:
  linux-container:
    docker:
      - file: "./linux.Dockerfile"

jobs:
  build-in-linux:
    executor: linux-container
    steps:
      - build
      - test
